### ISSUE TITLE
mysqldef: dereferencing `nil` in `generateIndexOptionDefinition` when upgrading MySQL schema

### ISSUE THREAD

**Issue by shunf4** [k0kubun/sqldef#150]
## --export output

databse `test`:
```
CREATE TABLE `testtable` (
  `id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `id_IDX` (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

database `test2`:
```
CREATE TABLE `testtable` (
  `id` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

## Input SQL

Executing command:

```
mysqldef -u [...] -p [...] -h [...] -P [...] --export test | mysqldef -u [...] -p [...] -h [...] -P [...] test2 --dry-run
```

## Current output

```
$ mysql -u [...] -p  --host [...] --port [...]
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 5
Server version: 10.6.4-MariaDB-1:10.6.4+maria~focal mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> CREATE DATABASE test;
Query OK, 1 row affected (0.104 sec)

MariaDB [(none)]> USE test;
Database changed
MariaDB [test]> CREATE TABLE testtable (
    -> id INTEGER NOT NULL,
    -> PRIMARY KEY (id),
    -> KEY id_IDX (id) using BTREE
    -> );
Query OK, 0 rows affected (0.028 sec)

MariaDB [test]> CREATE DATABASE test2;
Query OK, 1 row affected (0.114 sec)

MariaDB [test]> USE test2;
Database changed
MariaDB [test2]> CREATE TABLE testtable (
    -> id INTEGER NOT NULL,
    -> PRIMARY KEY (id)
    -> );
Query OK, 0 rows affected (0.017 sec)

MariaDB [test2]> ^DBye
```

```
$ mysqldef -u [...] -p [...] -h [...] -P [...] --export test | mysqldef -u [...] -p [...] -h [...] -P [...] test2 --dry-run
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x7e98ea]

goroutine 1 [running]:
github.com/k0kubun/sqldef/schema.(*Generator).generateIndexOptionDefinition(0xc0000d7c58, 0xc000098228, 0x1, 0x1, 0x1, 0xc000088dd0)
        C:/Users/shunf4/go/pkg/mod/github.com/k0kubun/sqldef@v0.11.0/schema/generator.go:949 +0x42a
github.com/k0kubun/sqldef/schema.(*Generator).generateAddIndex(0xc0000d7c58, 0xc0000accd0, 0x9, 0xc0000acd78, 0x6, 0xc0000acd6b, 0x3, 0xc000
112ff0, 0x1, 0x1, ...)
        C:/Users/shunf4/go/pkg/mod/github.com/k0kubun/sqldef@v0.11.0/schema/generator.go:891 +0x21f
github.com/k0kubun/sqldef/schema.(*Generator).generateDDLsForCreateTable(0xc0000d7c58, 0xc0000acec0, 0x9, 0xc00013c0e0, 0x1, 0x1, 0xc0000eed
c0, 0x1, 0x1, 0xbb1770, ...)
        C:/Users/shunf4/go/pkg/mod/github.com/k0kubun/sqldef@v0.11.0/schema/generator.go:474 +0x1938
github.com/k0kubun/sqldef/schema.(*Generator).generateDDLs(0xc0000d7c58, 0xc000088d60, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0xc0000d7c78)
        C:/Users/shunf4/go/pkg/mod/github.com/k0kubun/sqldef@v0.11.0/schema/generator.go:89 +0x1b78
github.com/k0kubun/sqldef/schema.GenerateIdempotentDDLs(0x0, 0xc00012a000, 0x95, 0xc0000de0e0, 0x70, 0x0, 0xb6e480, 0x0, 0xc0000d7d70, 0x65e
6df)
        C:/Users/shunf4/go/pkg/mod/github.com/k0kubun/sqldef@v0.11.0/schema/generator.go:76 +0x31e
github.com/k0kubun/sqldef.Run(0x0, 0x9e2870, 0xc000118060, 0xc000098168)
        C:/Users/shunf4/go/pkg/mod/github.com/k0kubun/sqldef@v0.11.0/sqldef.go:43 +0x2b1
main.main()
        C:/Users/shunf4/go/pkg/mod/github.com/k0kubun/sqldef@v0.11.0/cmd/mysqldef/mysqldef.go:106 +0x25c
```

## Expected output

```
$ mysqldef -u [...] -p [...] -h [...] -P [...] --export test | mysqldef -u [...] -p [...] -h [...] -P [...] test2 --dry-run
(Some SQL, without error)
```

**Comment by k0kubun** [comment]
Thanks. Fixed the issue in v0.11.1.
