### ISSUE TITLE
[psqldef] Cannot parse `t.*` in `select t.* from t;` 

### ISSUE THREAD

**Issue by halwhite** [k0kubun/sqldef#397]
## Platform
In version 0.11.50 (that we are using now), Input SQL is loaded correctly, but in version 0.15.24, an error occurs when loading.

* OS: macOS
* RDBMS: PostgreSQL
* Version: 0.15.24

## --export output
```
-- No table exists --
```

## Input SQL
```
CREATE TABLE
  users (
    usre_id INT PRIMARY KEY,
    name VARCHAR(100) NOT NULL
  );

CREATE VIEW
  users_view AS
SELECT
  u.*
FROM
  users AS u;
```

## Current output

```
panic: interface conversion: pg_query.isNode_Node is *pg_query.Node_AStar, not *pg_query.Node_String_

goroutine 1 [running]:
github.com/k0kubun/sqldef/database/postgres.PostgresParser.parseExpr({{0x0?}, 0x0?}, 0x0?)
        /home/runner/work/sqldef/sqldef/database/postgres/parser.go:330 +0x8c4
github.com/k0kubun/sqldef/database/postgres.PostgresParser.parseResTarget({{0x0?}, 0x0?}, 0x400009cba0)
        /home/runner/work/sqldef/sqldef/database/postgres/parser.go:231 +0x28
github.com/k0kubun/sqldef/database/postgres.PostgresParser.parseSelectStmt({{0x1?}, 0x0?}, 0x40001c0000)
        /home/runner/work/sqldef/sqldef/database/postgres/parser.go:198 +0x1a8
github.com/k0kubun/sqldef/database/postgres.PostgresParser.parseViewStmt({{0x20?}, 0x40?}, 0x40000f5f80)
        /home/runner/work/sqldef/sqldef/database/postgres/parser.go:169 +0x90
github.com/k0kubun/sqldef/database/postgres.PostgresParser.parseStmt({{0x40003160f7?}, 0x60?}, 0x40001d7701?)
        /home/runner/work/sqldef/sqldef/database/postgres/parser.go:76 +0x120
github.com/k0kubun/sqldef/database/postgres.PostgresParser.Parse({{0x200?}, 0x1?}, {0x40003160a0, 0x95})
        /home/runner/work/sqldef/sqldef/database/postgres/parser.go:45 +0x14c
github.com/k0kubun/sqldef/schema.ParseDDLs(0x0?, {0x40bf20?, 0x40001a8fb0?}, {0x40003160a0?, 0x40001d7928?}, {0x40001a93b0, 0x6})
        /home/runner/work/sqldef/sqldef/schema/parser.go:463 +0x48
github.com/k0kubun/sqldef/schema.GenerateIdempotentDDLs(0x1, {0x40bf20, 0x40001a8fb0}, {0x40003160a0?, 0x1000?}, {0x0, 0x0}, {{0x0, 0x0, 0x0}, ...}, ...)
        /home/runner/work/sqldef/sqldef/schema/generator.go:62 +0x64
github.com/k0kubun/sqldef.Run(0x1, {0x40e578, 0x40002fa360}, {0x40bf20, 0x40001a8fb0}, 0x400022d6c0)
        /home/runner/work/sqldef/sqldef/sqldef.go:60 +0x208
main.main()
        /home/runner/work/sqldef/sqldef/cmd/psqldef/psqldef.go:148 +0x2dc
```

## Expected output
create view without panic

**Comment by k0kubun** [comment]
Thank you for reporting it. Could you check which version between 0.11.50 and 0.15.24 introduced this problem?

**Comment by halwhite** [comment]
by git bisect, https://github.com/k0kubun/sqldef/commit/e1bba65a5b055eb9b1d639d3a77249ed68a215cc introduced this problem.

**Comment by k0kubun** [comment]
Thanks for finding it. I think, while the version before that revision happens to "work", it's not how it's supposed to parse the expression. So both versions seem broken in different ways.

The right solution to it is probably checking `*pg_query.Node_AStar` and using `"*"` for that type instead of `field.Node.(*pgquery.Node_String_).String_.Str`. Would you be interested in writing a pull request to fix it that way?

**Comment by hokaccha** [comment]
The bug crashing on `select *` has been fixed and this issue is closed. We know that other problems can occur, see this PR for more information. https://github.com/k0kubun/sqldef/pull/423
