### ISSUE TITLE
psqldef panics, abort with syntax error on valid VIEWs

### ISSUE THREAD

**Issue by chumaltd** [k0kubun/sqldef#454]
Hi, I hit into 2 cases of psqldef parse error on VIEW.  
And, I extracted reproducible DDL for each one. They may look meaningless, but taken from actual use cases.

I think `--skip-view` option would be helpful for an escape hatch, as table operation looks much stable and Views can be `CREATE OR REPLACE`ed by psql.

## Platform

* OS: Linux
* RDBMS: PostgreSQL
* Version: v0.16.9

### --export output

```bash
$ psqldef -Upostgres -hlocalhost -p5432 --export some_db

2023/10/23 12:50:14 found syntax error when parsing DDL "CREATE VIEW public.any_array AS SELECT 1 AS "?column?" WHERE (1 = ANY (ARRAY[1, 4, 5]))": syntax error at position 79 near '1'
```

### Input SQL

```sql
CREATE VIEW any_array AS SELECT 1 WHERE 1 in (1, 4, 5);
```

PostgreSQL internally transforms this as follows:

```sql
CREATE VIEW any_array AS SELECT 1 WHERE 1 = ANY(ARRAY[1, 4, 5]);
```

### --export output

```bash
$ psqldef -Upostgres -hlocalhost -p5432 --export some_db

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xbf86e9]

goroutine 1 [running]:
github.com/k0kubun/sqldef/database/postgres.PostgresParser.parseExpr({{0x0?}, 0x0?}, 0x0?)
        /home/runner/work/sqldef/sqldef/database/postgres/parser.go:293 +0x29
github.com/k0kubun/sqldef/database/postgres.PostgresParser.parseExpr({{0x0?}, 0x0?}, 0x0?)
        /home/runner/work/sqldef/sqldef/database/postgres/parser.go:351 +0xbe6
github.com/k0kubun/sqldef/database/postgres.PostgresParser.parseResTarget({{0x203000?}, 0x0?}, 0xc0000c23c0)
        /home/runner/work/sqldef/sqldef/database/postgres/parser.go:281 +0x23b
github.com/k0kubun/sqldef/database/postgres.PostgresParser.parseSelectStmt({{0x0?}, 0x0?}, 0xc000141b80)
        /home/runner/work/sqldef/sqldef/database/postgres/parser.go:201 +0x1f6
github.com/k0kubun/sqldef/database/postgres.PostgresParser.parseViewStmt({{0x1?}, 0x68?}, 0xc000303f00)
        /home/runner/work/sqldef/sqldef/database/postgres/parser.go:172 +0xaf
github.com/k0kubun/sqldef/database/postgres.PostgresParser.parseStmt({{0xc00040527f?}, 0x0?}, 0xc0003d0fa0?)
        /home/runner/work/sqldef/sqldef/database/postgres/parser.go:76 +0x185
github.com/k0kubun/sqldef/database/postgres.PostgresParser.Parse({{0x2b?}, 0x40?}, {0xc000400000, 0x5498})
        /home/runner/work/sqldef/sqldef/database/postgres/parser.go:45 +0x195
github.com/k0kubun/sqldef/schema.ParseDDLs(0x203000?, {0x410700?, 0xc000129280?}, {0xc000400000?, 0xf4240?}, {0xc00003a600, 0x6})
        /home/runner/work/sqldef/sqldef/schema/parser.go:464 +0x62
github.com/k0kubun/sqldef.Run(0x1, {0x412e18, 0xc00027c360}, {0x410700, 0xc000129280}, 0xc000197730)
        /home/runner/work/sqldef/sqldef/sqldef.go:44 +0x152
main.main()
        /home/runner/work/sqldef/sqldef/cmd/psqldef/psqldef.go:148 +0x3f3
```

### Input SQL

```sql
CREATE VIEW nested_case AS
  SELECT CASE
    WHEN 1 > 6 THEN 3
    ELSE CASE 4 + 1
      WHEN 1 THEN 1
      ELSE NULL
    END
END AS value;
```

**Comment by k0kubun** [comment]
> I hit into 2 cases of psqldef parse error on VIEW.

Thank you for reporting them. I think both of them are described well. Could you, however, split an issue for these two different cases? They are fairly independent problems, so it'd be useful if they have different issue numbers.

> I think --skip-view option would be helpful for an escape hatch

Sure. I'm open to adding one to psqldef while it's currently limited to mysqldef. Would you be interested in filing a pull request to add that to psqldef?

**Comment by chumaltd** [comment]
@k0kubun  Thank you for your confirmation.
Yes, they should have different causes, and I just split into each issue.

> Sure. I'm open to adding one to psqldef while it's currently limited to mysqldef. Would you be interested in filing a pull request to add that to psqldef?

It's nice to hear that.
Actually I haven't written a line of golang, but I'll just try for the next several days.
I feel much potential with `--skip-view` option.

**Comment by chumaltd** [comment]
MATERIALIZED VIEW gets the same behavior as VIEW.

### --export output

```bash
$ psqldef -Upostgres -hlocalhost -p5432 --export some_db

2023/10/28 11:30:44 found syntax error when parsing DDL "CREATE MATERIALIZED VIEW public.any_array AS SELECT 1 AS "?column?" WHERE (1 = ANY (ARRAY[1, 4, 5]))": syntax error at position 92 near '1'
```

### Input SQL

```sql
CREATE MATERIALIZED VIEW any_array AS SELECT 1 WHERE 1 in (1, 4, 5);
```
